services:
  db:
    image: mysql:9
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=app
    ports:
      - "3306:3306"
    volumes:
      - ../scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
